name: CI + CD

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        cd foo
        pip install -r requirements.txt
        pip install pylint
        pylint flaskapp.py

  deploy:
    needs: lint
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        cd foo
        docker build -t flask-nginx-app:${{ github.sha }} .

    - name: Deploy with Helm
      run: |
        cd foo
        helm upgrade --install flask-nginx ./helm-chart --namespace default --set image.repository=flask-nginx-app --set image.tag=${{ github.sha }}
